---
# Firewall configuration.
firewall_allowed_tcp_ports:
  - 22
  # For Gluster.
  - 111
  # Port-mapper for Gluster 3.4+.
  # - 2049
  # Gluster Daemon.
  - 24007
  # 24009+ for Gluster &lt;= 3.3; 49152+ for Gluster 3.4+.
  - 24009
  - 24010
  # Gluster inline NFS server.
  - 38465
  - 38466
firewall_allowed_udp_ports:
  - 111

# Gluster configuration.
gluster_mount_dir: /mnt/gluster
gluster_brick_dir: /srv/gluster/brick
gluster_brick_name: gluster

hacluster_account:
  username: hacluster
  password: clustering

# user used for authorizing cluster nodes
cluster_user: hacluster
cluster_user_pass: testtest
# group to which cluster user belongs (should be 'haclient')
cluster_group: haclient

# name of the cluster
cluster_name: pacemaker

# configuration of firewall for clustering, NOTE in RHEL/Centos 6 this replaces iptables configuration file!
cluster_firewall: true

# enable cluster on boot
cluster_enable_service: true

# configure cluster with fence_xvm fencing device ?
# this will copy /etc/cluster/fence_xvm.key to nodes and add fencing devices to cluster
# NOTE: you need to define 'hypervisor_name' in the inventory for each cluster node
cluster_configure_fence_xvm: true
